AWSTemplateFormatVersion: "2010-09-09"
Description: "Deploys the Hashicorp Vault helm chart into an existing kubernetes cluster (qp-1qmcrhdml)"
Metadata:
  QSLint:
    Exclusions: [W9002, W9003, W9004, W9006]
Parameters:
  ClusterName:
    Type: String
    Description: Amazon EKS Cluster
  ChartURI:
    Default: ""
    Description: "Vault Helm Chart URI, either github or s3 location eg: 'https://github.com/hashicorp/vault-helm/archive/v0.5.0.tar.gz' or 's3://<bucket>/<prefix>/charts/vault-helm-0.5.0.tar.gz'"
    Type: String
Resources:
  HashicorpVaultHelmChart:
    Type: "AWSQS::Kubernetes::Helm"
    Properties:
      ClusterID: !Ref ClusterName
      Chart: !Ref ChartURI
      Values: 
        ha.enabled: true
        ha.nodes: 5
Outputs:
  HashicorpVaultReleaseName:
    Value: !Ref HashicorpVaultHelmChart
