AWSTemplateFormatVersion: "2010-09-09"
Description: "Deploys the HashiCorp Vault helm chart into a Kubernetes cluster (qs-1qmcrhdml)"
Parameters:
  ACMSSLCertificateARN:
    Type: String
    Description: Amazon EKS Cluster
    AllowedPattern: (^$|^arn:(aws[a-zA-Z-]*)?:acm:[a-z]{2}((-gov)|(-iso(b?)))?-[a-z]+-\d{1}:\d{12}:certificate\/[a-zA-Z0-9-_]+$)
    ConstraintDescription: Must be a valid ACM Certificate ARN or a blank string
Resources:
  Foo:
    Type: AWS::S3::Bucket